### PR TITLE
Reinstate Turing cluster

### PR DESCRIPTION
**Pull request by callummole**
Ref: #495

The cluster is up and running again. Reinstating the Turing cluster to it's pre-paused levels (see #2150).

### CODE REVIEW

**Comment by minrk** [comment]
Woo!

**Comment by minrk** [comment]
@callummole almost! Looks like while turing was down, we've updated to require k8s 1.19, and turing is still on 1.18. How easy is it for you to run a cluster upgrade?

**Comment by minrk** [comment]
If that's not feasible, I can try to handle the difference with Capability detection

**Comment by callummole** [comment]
@minrk `az aks get-upgrades` is showing available upgrades as `1.21.7` and `1.21.9`. I guess it is showing me only the most recent possible? I can try and force an upgrade to `1.19.X`?

**Comment by minrk** [comment]
1.21 is fine, too! #2157 means we support 1.21

**Comment by minrk** [comment]
I had the capability detection lying around in my git history for #2157, so #2162 means there's no time pressure now.

**Comment by callummole** [comment]
@minrk I'm happy to upgrade it right now? It may be unavailable for a wee bit during the upgrade.

**Comment by callummole** [comment]
Successfully upgraded to 1.21.9

**Pull request merged**
