### PR TITLE
repo2docker: b20eb6a8...d72c6018

### PR DESCRIPTION
**Pull request by henchbot**
This is a repo2docker version bump. See the link below for a diff of new changes:

https://github.com/jupyter/repo2docker/compare/b20eb6a8...d72c6018 

Associated PRs:

### CODE REVIEW

**Comment by betatim** [comment]
With @minrk's change in https://github.com/jupyter/repo2docker/pull/777 I think we broke the way henchbot finds the related commits. We also need to tidy up the tag as it should be `0.10.0-17.g82cd28d` not `0.10.0-17.g82cd28d.dirty`

**Comment by bitnik** [comment]
@betatim but tags in docker hub are also with ".dirty".

And another thing I dont understand is "g82cd28d". It must be the latest commit hash in git, right? But it doesnt exist in git history or maybe I am confused.

**Comment by bitnik** [comment]
"g82cd28d" -> without "g" in the beginning (82cd28d) it is the last commit hash.

**Comment by betatim** [comment]
@henchc from what @bitnik said it is probably the leading `g` in the hash that causes the associated PRs list to be empty in henchbot.

**Comment by henchc** [comment]
Thanks @betatim @bitnik , I'm just catching up here. So to confirm, the actual file diff is correct? But the commit from github is no longer identified so it breaks finding associated PRs and in the titling for the compare URL?

Can someone explain in one sentence where the "g" and "dirty" comes from?

**Comment by betatim** [comment]
The new tag comes from asking versioneer to tell us the version of repo2docker we are running. Versioneer prints the latest release tag, how many commits have passed since, the style of version control you use (`g` for git in our case), the commit hash and then it adds "dirty" if the repo contains uncommitted changes.

That "dirty" shows up is a bug that should be fixed now, so it shouldn't show up anymore.

**Comment by betatim** [comment]
The diff URL also contains weird tags so that probably also didn't work properly :(

**Pull request merged**
