### PR TITLE
whitelist rsync, xroot ports

### LINKED ISSUE #614: open outbound rsync on port tcp/873
@chennesy and I have a use case that uses rsync to transfer data from a remote repository.

It would be helpful to allow outbound connections via the rsync protocol port (tcp/873) so that commands like this will work for rsync’ing data from a repository which requires using the rsync protocol (and that do not allow ssh-based transport) :
```
%%bash
htid2rsync --f vol_ids_5.txt | rsync -azv --files-from=- data.sharc.hathitrust.org::features/ local-folder/
```

You can see a real-life example accessing the HathiTrust Digital Library which provides access to millions of digitized books for use by researchers: https://github.com/aculich/htrc

Currently this example hangs until rsync has a timeout since it cannot reach hathitrust.org via tcp/873.

### PR DESCRIPTION
**Pull request by minrk**
this is not run on CI, firewall-rules must be run manually after merge to unblock the ports

closes #614

### CODE REVIEW

**Comment by lukasheinrich** [comment]
let me know if you need someone to test the xrootd port. Or I can send some instructions.

**Comment by betatim** [comment]
For rsync and xrootd should we use a whitelist of hosts as well? Not sure I could propose a starting list so this is more a thought. Otherwise LGTM.

**Comment by minrk** [comment]
> For rsync and xrootd should we use a whitelist of hosts as well?

I'd really like to, but we can't do this easily. Our firewall blocking occurs at the CIDR level (ip address ranges), so we would need to resolve hosts with DNS and constantly update the associated ip addresses in the filter.

**Comment by betatim** [comment]
Should we merge this? I don't remember why it is sitting here, so 👍 on merging.

**Comment by lukasheinrich** [comment]
is there a way to test this? an example xrootd path would be (CMS open data)

```
root://eospublic.cern.ch//eos/opendata/cms/Run2011A/ElectronHad/AOD/12Oct2013-v1/20001/001F9231-F141-E311-8F76-003048F00942.root
```

**Comment by betatim** [comment]
Merged, once the deploy is done you should be able to test it on mybinder.org @lukasheinrich

**Comment by minrk** [comment]
BTW, firewall-rules is *not* run on CI, but I just ran it so this should be in effect now.

**Comment by aculich** [comment]
Thanks @minrk I've confirmed that this works for `rsync` with the original repository in question that motivated this change: https://github.com/aculich/htrc

image

**Pull request merged**
