### PR TITLE
Bump quota for scipy 2020 repos to 300

### PR DESCRIPTION
**Pull request by manics**
Bump quotas for scipy 2020 repositories:
- https://github.com/jupyterhub/team-compass/issues/310
- #1476 
- #1477 
- #1479 
- #1480

### CODE REVIEW

**Comment by choldgraf** [comment]
What if we made one more post on twitter about this to see if any last-second tutorials wanted a resource bump, and then merged this after a day? Just trying to anticipate the "oh what about us I forgot to ask" contingent :-)

**Comment by manics** [comment]
Sounds good! First tutorial is Monday 9am CDT (14:00 UTC)

**Comment by manics** [comment]
Added https://github.com/jupyterhub/mybinder.org-deploy/issues/1483

**Comment by manics** [comment]
It's starting in 30 mins, merging!

**Comment by manics** [comment]
Turing is failing: https://travis-ci.org/github/jupyterhub/mybinder.org-deploy/builds/705399693
```
Merged "turing" as current context in /home/travis/.kube/config

Client version: v2.16.3, Server version: v2.16.3

$HELM_HOME has been configured at /home/travis/.helm.

Not installing Tiller due to 'client-only' flag having been set

deployment "tiller-deploy" successfully rolled out

Updating network-bans for turing

Starting helm upgrade for turing

E0706 13:50:31.704220   13184 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:42131->127.0.0.1:33424: write tcp4 127.0.0.1:42131->127.0.0.1:33424: write: broken pipe

UPGRADE FAILED

Error: a release named turing is in use, cannot re-use a name that is still in use

Error: UPGRADE FAILED: a release named turing is in use, cannot re-use a name that is still in use

Traceback (most recent call last):

  File "./deploy.py", line 302, in <module>

    main()

  File "./deploy.py", line 298, in main

    deploy(args.release)

  File "./deploy.py", line 216, in deploy

    subprocess.check_call(helm)

  File "/opt/python/3.6.7/lib/python3.6/subprocess.py", line 291, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['helm', 'upgrade', '--install', '--namespace', 'turing', 'turing', 'mybinder', '--force', '--cleanup-on-fail', '-f', 'config/turing.yaml', '-f', 'secrets/config/common.yaml', '-f', 'secrets/config/turing.yaml']' returned non-zero exit status 1.

The command "# Stage 5, Step 4: Deploy to production on Turing k8s

      python ./deploy.py turing turing

      " failed and exited with 1 during .

Your build has been stopped.
```
@sgibson91

**Comment by sgibson91** [comment]
@manics Did OVH pass?

**Comment by sgibson91** [comment]
I have no idea how to fix this without deleting everything and doing a fresh install of the chart 😞

**Comment by sgibson91** [comment]
#1484

**Comment by choldgraf** [comment]
no worries @sgibson91 - that is the beauty of kubernetes!! thanks for working to debug :-)

**Pull request merged**
