### PR TITLE
repo2docker: 8d8c21e5...9bcc41a

### PR DESCRIPTION
**Pull request by sgibson91**
This is a repo2docker version bump. See the link below for a diff of new changes:

https://github.com/jupyter/repo2docker/compare/8d8c21e5...9bcc41a

### CODE REVIEW

**Comment by choldgraf** [comment]
let's give it a whirl and see how it goes!

thanks for the update @sgibson91 - in the future, feel free to merge these straight away, we can check the deploy logs and if they don't work, we can always roll-back the PR

**Comment by betatim** [comment]
I don't think @sgibson91 can press the merge button. At least I don't think so. Realising this is what made me write https://github.com/jupyterhub/team-compass/issues/148 as a way to fix this. Maybe the problem never existed?

**Comment by choldgraf** [comment]
ah dang, I didn't realize that but it makes sense

**Comment by sgibson91** [comment]
Can confirm that I did not have a merge button 😄

**Comment by choldgraf** [comment]
hmmm, we are still failing on test_build w/ timeout errors. Anybody have thoughts if this is a travis problem or a repo2docker problem?

https://travis-ci.org/jupyterhub/mybinder.org-deploy/jobs/517418152#L1051

**Comment by choldgraf** [comment]
hmmmm, this one didn't pass staging on a second pass, so I'm going to revert this PR for now so that we can either debug, or try again later in case we have a travis and/or GKE burp

**Comment by betatim** [comment]
Looking at `binder-staging` with `kubectl get pods` I saw a lot of build pods hanging there in status `ImagePullBackOff`.

I then described one of them and it was failing with `Back-off pulling image "jupyter/repo2docker:9bcc41a"`. So either there was a hiccup with pushing the repo2docker image to docker hub or we made a typo in the tag we are deploying.

**Comment by betatim** [comment]
Let's make another attempt tomorrow. So far everything worked as designed and @sgibson91 is getting the full deployment experience with reverts and everything 😃.

What could kind of tool could we design ourselves to catch this kind of typo? I am not sure I know one other than a script in the CI that checks if the tags we set actually exist on docker hub and gives a clear error message saying "that tag doesn't exist, can't deploy". Does someone know if we can check what tags exist without having to pull the image?

**Comment by choldgraf** [comment]
happy to help be on-call during a new deployment tomorrow!

re: the copypasta issue, maybe an easy first step is to print *just* the updated tag just after each line of the "new commits" script. That way you could quickly double-click the tag to copy

**Comment by betatim** [comment]
I made #935 to discuss this.

**Comment by sgibson91** [comment]
I had noticed that GitHub "shortened" commit hash, in the r2d repo, was one character less than the old hash but I didn't realise this was a dependency!

**Pull request merged**
