### PR TITLE
Changing the OVH registry to use

### PR DESCRIPTION
**Pull request by mael-le-gal**
As describe in the issues [here](https://github.com/jupyterhub/mybinder.org-deploy/issues/1016) and [here](https://github.com/jupyterhub/mybinder.org-deploy/issues/1031) we had some problem of reliability with the current docker registry used by the `ovh` stack.

As we just launched a new service of managed docker registry in `beta` it would be a good idea to switch on it and see if it improve anything.

I ordered a registry for you and here is the [URL to the admin interface](https://dlqpwel7.gra5.container-registry.ovh.net/harbor/sign-in) 

This service is powered by the open source project [Harbor](https://github.com/goharbor/harbor) and you can log in with the credentials that you'll find on this PR.

I hope that my configuration is `ok` as I didn't have the chance to test it. ⚠️ 
Maybe I should switch the OVH traffic to 0% also on this PR in order for me to test that everything is OK before switching again to 15%. **What do you think ?**

### CODE REVIEW

**Comment by choldgraf** [comment]
Thanks for digging into this and trying to improve things!

I'll trust your judgment on whether it's a good idea to try out this new image service...I agree we should move the traffic down to 0%, see that it works, and then gradually bump up over time after that.

Will merge this in a few hours if nobody else disagrees!

**Comment by mael-le-gal** [comment]
I just push the change to switch the ovh traffic to 0%. It will take effect at the merge.
I'll check if everything is alright with this new registry tomorrow

**Comment by betatim** [comment]
@mael-le-gal I like your plan (new registry, 0% traffic and merge tomorrow).

**Comment by choldgraf** [comment]
Cool, I'll hold off on merging then, but please do press the green button whenever you like!

**Comment by mael-le-gal** [comment]
I'm ready for the merge

**Comment by betatim** [comment]
Merged :)

**Comment by betatim** [comment]
```
[E 190627 11:57:55 web:1621] Uncaught exception GET /build/gh/binder-examples/requirements/master (31.10.137.255)
    HTTPServerRequest(protocol='https', host='ovh.mybinder.org', method='GET', uri='/build/gh/binder-examples/requirements/master', version='HTTP/1.1', remote_ip='31.10.137.255')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/binderhub/builder.py", line 273, in get
        image_manifest = await self.registry.get_image_manifest(*'/'.join(image_name.split('/')[-2:]).split(':', 1))
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python3.6/site-packages/binderhub/registry.py", line 218, in get_image_manifest
        resp = yield client.fetch(req)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
    tornado.httpclient.HTTPError: HTTP 401: Unauthorized
```
from the log of the binderhub pod

**Comment by betatim** [comment]
@mael-le-gal I'm on https://gitter.im/jupyterhub/mybinder.org-deploy might be easier for debugging.

**Comment by betatim** [comment]
I think the problem is that the "home made" docker registry API client we have in BinderHub doesn't speak the full docker protocol. This means when we configure just a username and password it does basic auth. However Harbor is configured to use token based auth.

When you make a request to Harbor with user/pw it will respond with a 401 and information in the headers about the location of the token service. The docker client will then go there to get a token. Howerver in Binderhub we don't do that.

The quick fix is to configure the token URL "by hand" to `https://dlqpwel7.gra5.container-registry.ovh.net/service/token` which I got from:
```python
requests.get("https://dlqpwel7.gra5.container-registry.ovh.net/v2/binder/{img}/manifests/{tag}".format(img="mlg-test", tag="latest"), auth=(u, pw))
```
and looking at the headers (in particular `Www-Authenticate`).

Or we extend BinderHub itself to recognise this and do what the docker client does (follow the information in the `Www-Authenticate` header).

**Comment by mael-le-gal** [comment]
On the previous registry we set this configuration :  
```
DockerRegistry:
      token_url: https://auth-binder-registry.mybinder.ovh/auth?service=binder-
```

I need to figure it out if it will work with : 
```
DockerRegistry:
      token_url: https://dlqpwel7.gra5.container-registry.ovh.net/service/token
```

**Comment by mael-le-gal** [comment]
Ok I think that will solve the issue, I make the changes and push a new PR

**Pull request merged**
