### PR TITLE
Add Site Reliabillity Guide

### PR DESCRIPTION
**Pull request by willingc**
http://test-mybinder-deploy.readthedocs.io/en/sre-guide/

### CODE REVIEW

**Comment by minrk** [comment]
Very nice!

**Comment by choldgraf** [comment]
wow this is great, thanks a lot @willingc :-D

two quick things:

1. It seems that this is duplicating some content we had in various markdown files before (e.g. I think in `contributing.md`. Should we remove the old content so that it's compiled in one place here?
2. I'll take a closer look through all the text when you remove the WIP!

**Comment by willingc** [comment]
I've updated the guide to a cleaner style similar to BinderHub. Links have been checked and updated.

I think what's left to do is decide which content should remain in the README and what could be moved into the Site Reliability Guide. My recommendation would be to do that in a separate PR.

**Comment by betatim** [comment]
After your link fixes did you also update the rendered version at: http://test-mybinder-deploy.readthedocs.io/en/sre-guide/ ? I just browsed it and the incident_template link there doesn't work.

**Comment by willingc** [comment]
Good catch @betatim. You are better than `make linkcheck` which passed cleanly. Ugh recommonmark and markdown. I made some changes. This should be good to go.

**Comment by minrk** [comment]
Thanks @willingc!

**Pull request merged**
