### PR TITLE
Add incident report for repo2docker upgrade and build cache wipe

### PR DESCRIPTION
**Pull request by betatim**
Incident report for yesterday's repo2docker upgrade bonanza.

### CODE REVIEW

**Comment by betatim** [comment]
Need to reflect on our todo's from this that should be listed at the end of this report before merging.

**Comment by choldgraf** [comment]
I'm curious what it meant to add two new nodes, but as a new "node pool" instead of just adding nodes to the current setup. Was there a specific reason for that?

**Comment by betatim** [comment]
The node pool we have is set to auto-scale. This means even if you manually increase the minimum size of the cluster the auto-scaler won't actually deploy those nodes unless it also thinks they are needed. This means if your cluster is "empty" as determined by the auto-scaler it won't grow the cluster.

In this case I wanted to have extra nodes that could help out with builds.

**Comment by betatim** [comment]
Merged this now as I won't get around to seriously thinking about other action items.

**Pull request merged**
