### PR TITLE
cert-manager 1.1

### PR DESCRIPTION
**Pull request by minrk**
switches to 'replace' for CRDs based on recommendation [here](https://cert-manager.io/docs/installation/upgrading/upgrading-1.1-1.2)

### CODE REVIEW

**Comment by minrk** [comment]
please /test-this-pr

**Comment by minrk** [comment]
please /test-this-pr

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2237).

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2237).

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2237).

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2237).

**Comment by minrk** [comment]
Looks like we may need to run this twice to succeed

**Pull request merged**
