### PR TITLE
remove legacy ovh from federation

### PR DESCRIPTION
**Pull request by minrk**
we have a new ovh cluster to replace it

and the old one seems to be unhealthy

### CODE REVIEW

**Comment by minrk** [comment]
Does not remove config yet, just from federation and CD

**Comment by minrk** [comment]
cc @mael-le-gal the OVH2 member is working at least as well as the old OVH cluster. This PR removes the old OVH cluster from the federation.

@mael-le-gal do you have a plan for shutting down the old cluster?

**Comment by mael-le-gal** [comment]
@minrk if you tell me that everything is good on your side I can shut down the old cluster

**Comment by manics** [comment]
Testing today, it seems ovh is working but ovh2 isn't!

**Review by manics — APPROVED** [review]
Shall we merge this?

**Comment by minrk** [comment]
Yeah, let's go ahead

**Comment by manics** [comment]
This failed to deploy on staging:
```
$ kubectl -n staging get pods -lapp=federation-redirect
NAME                                   READY   STATUS             RESTARTS         AGE
federation-redirect-74b758f5bd-4p82f   1/1     Running            0                6d11h
federation-redirect-85f7457885-d4z2m   0/1     CrashLoopBackOff   16 (4m34s ago)   61m
federation-redirect-85f7457885-nj2dt   0/1     CrashLoopBackOff   16 (4m17s ago)   61m

$ kubectl -n staging logs federation-redirect-85f7457885-d4z2m
Traceback (most recent call last):
  File "/srv/app.py", line 76, in <module>
    CONFIG = get_config(CONFIG_PATH)
  File "/srv/app.py", line 69, in get_config
    config["hosts"][h]["url"] = config["hosts"][h]["url"].rstrip("/")
KeyError: 'url'
```

**Comment by manics** [comment]
```
kubectl -n staging get cm federation-redirect -o jsonpath='{.data.config\.json}' |jq
```
```json
{
  "check": {
    "failed_period": 90,
    "jitter": 0.1,
    "period": 15,
    "retries": 5,
    "timeout": 5
  },
  "enabled": true,
  "host": "staging.mybinder.org",
  "hosts": {
    "gesis": {
      "health": "https://gesis.mybinder.org/health",
      "url": "https://gesis.mybinder.org",
      "versions": "https://gesis.mybinder.org/versions",
      "weight": 0
    },
    "gke": {
      "health": "https://gke2.staging.mybinder.org/health",
      "prime": true,
      "url": "https://gke2.staging.mybinder.org",
      "versions": "https://gke2.staging.mybinder.org/versions",
      "weight": 4
    },
    "ovh": {
      "weight": 0
    },
    "ovh2": {
      "health": "https://ovh2.mybinder.org/health",
      "url": "https://ovh2.mybinder.org",
      "versions": "https://ovh2.mybinder.org/versions",
      "weight": 100
    },
    "turing": {
      "health": "https://binder-staging.mybinder.turing.ac.uk/health",
      "url": "https://binder-staging.mybinder.turing.ac.uk",
      "versions": "https://binder-staging.mybinder.turing.ac.uk/versions",
      "weight": 4
    }
  },
  "image": {
    "name": "jupyterhub/mybinder.org-federation-redirect",
    "tag": "2020.12.4-0.dev.git.4827.heb171c8"
  },
  "load_balancer": "rendezvous",
  "nodeSelector": {},
  "pod_headroom": 10
}
```
`ovh` still has an entry

**Pull request merged**
