### PR TITLE
repo2docker: 8d8c21e5...9bcc41af

### PR DESCRIPTION
**Pull request by sgibson91**
Take 2!

This is a repo2docker version bump. See the link below for a diff of new changes:

https://github.com/jupyter/repo2docker/compare/8d8c21e5...9bcc41af

### CODE REVIEW

**Comment by choldgraf** [comment]
let's give it a whirl! I can confirm there are 8 characters in both hashes :-)

**Comment by choldgraf** [comment]
yay! upgrade worked! thanks so much @sgibson91 🎉

**Comment by sgibson91** [comment]
yay, thank you! 😊

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/mybinder-org-upgrades-and-updates/712/4

**Comment by choldgraf** [comment]
update added here: https://discourse.jupyter.org/t/mybinder-org-upgrades-and-updates/712/4

**Pull request merged**
