### PR TITLE
binderhub bump 80ac52c...6578e4d

### PR DESCRIPTION
**Pull request by choldgraf**
This is a BinderHub version bump. See the link
below for a diff of new changes:

https://github.com/jupyterhub/binderhub/compare/80ac52c...6578e4d

### CODE REVIEW

**Comment by choldgraf** [comment]
cc @betatim

**Comment by betatim** [comment]
@minrk should we have our wits about us when deploying the change to the CORS config? Otherwise I'd deploy this change this morning expecting that nothing happens beyond the badge changin.

**Comment by minrk** [comment]
There aren't CORS changes to deploy here. Sometimes the diffs linked from chart updates will include merge commits for the *previous* deploy that don't contain actual changes because the chart versions are based on the 'last change commit,' which is typically the commit that actually changed the file, not the merge when it landed in master. When in doubt, check the file changes, not the commit list for what's to be deployed.

This should be comfortably deployed now if you want to hit the button.

**Comment by betatim** [comment]
Thanks! I thought it was weird to only see the merge commit and no actual changes :-/

Deploy underway.

**Pull request merged**
