### PR TITLE
Attempt to wait for deployments to turn over before finishing deploy

### PR DESCRIPTION
**Pull request by yuvipanda**
--wait does not work well enough for our use cases.

### CODE REVIEW

**Comment by choldgraf** [comment]
so does the `kubectl rollout status` command hang until that component is ready or something?

**Comment by yuvipanda** [comment]
@choldgraf yep!

**Comment by choldgraf** [comment]
then I think this is a great addition :-)

I can test it out whenever we merge the loading page and I can try a deploy

**Comment by yuvipanda** [comment]
Some additional work is required wrt permissions (this one failed), am doing that now.

**Comment by choldgraf** [comment]
ping me when you want a review!

**Pull request merged**
