### PR TITLE
upgrade helm to 2.16.1

### PR DESCRIPTION
**Pull request by minrk**
and consolidate single $HELM_VERSION variable in .travis.yml

maybe this will fix the issue with secrets not being upgraded on staging?

### CODE REVIEW

**Comment by betatim** [comment]
Let's wait with deploying this until we can successfully deploy to prod again. Right now deploying to prod fails with:
```
Error: getting deployed release "prod": Stream error http2.StreamError{StreamID:0x8f89, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.

Traceback (most recent call last):

  File "./deploy.py", line 313, in <module>

    main()

  File "./deploy.py", line 309, in main

    deploy(args.release)

  File "./deploy.py", line 220, in deploy

    subprocess.check_call(helm)

  File "/opt/python/3.6.7/lib/python3.6/subprocess.py", line 291, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['helm', 'upgrade', '--install', '--namespace', 'prod', 'prod', 'mybinder', '--force', '--wait', '--timeout', '600', '-f', 'config/prod.yaml', '-f', 'secrets/config/common.yaml', '-f', 'secrets/config/prod.yaml']' returned non-zero exit status 1.

The command "# Stage 5, Step 2: Deploy to production

      HELM_VERSION=${TRAVIS_HELM_VERSION} python ./deploy.py prod prod-a

      " failed and exited with 1 during .

Your build has been stopped.
```

**Comment by consideRatio** [comment]
Why 2.16.1? I recall that has a serious bug and i know there is Helm v2.16.3 (12 days old) and 2.16.2 available also.

**Comment by minrk** [comment]
> Why 2.16.1? 

I just missed it when I was checking latest versions. It's 2.16.3 now.

**Comment by consideRatio** [comment]
LGTM - travis didn't run though ;/

**Comment by minrk** [comment]
Travis can't run on PRs, but it's passing on master now, so I think this should be okay to go ahead with.

**Pull request merged**
