### PR TITLE
add github client id, secret to common secret config

### PR DESCRIPTION
**Pull request by minrk**
and bump binderhub to support them (https://github.com/jupyterhub/binderhub/pull/165)

### CODE REVIEW

**Comment by yuvipanda** [comment]
Shouldnt we use a different key for staging and prod?

**Comment by minrk** [comment]
Maybe when it's doing something other than applying a rate limit. I think one token for the whole deployment makes sense for now.

**Comment by yuvipanda** [comment]
Cool! We can re examine if we actually start hitting the limits!

**Comment by minrk** [comment]
Sounds good. I'll deploy this to beta once staging is up and I've verified that it's using them correctly.

**Comment by minrk** [comment]
It's working. Yay!

**Pull request merged**
