### PR TITLE
Add GESIS team to list of people with secrets access

### PR DESCRIPTION
**Pull request by betatim**
@bitnik now has a copy of the key.

Once he has things working and can decrypt the secrets he should post a message here and we merge this.

### CODE REVIEW

**Comment by choldgraf** [comment]
I'm not sure if @bitnik 's 👍 means "all is working" or "message received and I'll let you know" 😄

**Comment by bitnik** [comment]
It was "message received and I'll let you know" :) and now I can confirm that I have the key, used it to decrypt the secrets and it worked.

-------

I have one question. Since we needed that key as GESIS Notebooks team, should we add GESIS Notebooks into the list? I would like to add the key into where we save secrets of GESIS Notebooks. What do you think?

**Comment by bitnik** [comment]
Btw with GESIS Notebooks team I mean @arnim and @MridulS.

**Comment by betatim** [comment]
I think changing the entry to reflect who has access is a good idea. Maybe we can list the individual usernames from the team? That way it is clear how to contact people. "GESIS team" is harder to turn into a email/GitHub notification.

**Comment by bitnik** [comment]
This works for us. I just shared the key with Arnim and Mridul.

**Comment by betatim** [comment]
Mergegd

**Pull request merged**
