### PR TITLE
JupyterLab 3.0: bump image prefix across the federation

### PR DESCRIPTION
**Pull request by minrk**
The order these things should be done in (they can be simultaneous, but some should not be before others):

1. update jupyterlab default UI in repo2docker (merged https://github.com/jupyterhub/repo2docker/pull/1035)
2. invalidate image cache by bumping image prefix (this pr). Cache should be invalidated with/after the r2d bump so we can assume new builds have lab 3.1.
3. bump binderhub filepath handling to use jupyterlab https://github.com/jupyterhub/binderhub/pull/1288 . This change is where we start to *apply* the assumption that cached builds have jupyterlab 3, and provide consistent UI for both filepath and default URLs.

This PR currently does all 3 (includes #2011 and #2014)

Purging the image cache means *lots* of new builds, and we will probably want to sweep out our old cache (related: #2012)

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
Thanks for your work on this Min! This LGTM!

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2009).

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2009).

**Comment by sgibson91** [comment]
Sidebar: We might need give the `GITHUB_TOKEN` extra permissions or use my token in the `report_status` job to avoid these errors

```
Error: Unhandled error: HttpError: Resource not accessible by integration
```

**Comment by minrk** [comment]
@sgibson91 yes! I was just writing a note about that. Deploy worked great, up to the delete & post-after-done steps, which need permissions.

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2009).

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2009).

**Comment by minrk** [comment]
okay, finally got it. Links to test on staging, all do what they are supposed to:

- regular binder link, [default url][]
- [with filepath][]
- [urlpath to opt-in to /tree][]

[default url]: https://staging.mybinder.org/v2/gh/binder-examples/conda/HEAD
[with filepath]: https://staging.mybinder.org/v2/gh/binder-examples/conda/HEAD?filepath=index.ipynb
[urlpath to opt-in to /tree]: https://staging.mybinder.org/v2/gh/binder-examples/conda/HEAD?urlpath=/tree/

**Comment by minrk** [comment]
Since this is disruptive and my day is ending, I'll deploy this to prod, tomorrow AM

**Pull request merged**
