### PR TITLE
Enable cryptnono on turing and ovh

### PR DESCRIPTION
**Pull request by yuvipanda**
Brings in https://github.com/yuvipanda/cryptnono/commit/6659c07a89bb565624c17a6a44410a65f88b2f08,
https://github.com/yuvipanda/cryptnono/commit/571fa9615a9d30a22a42ef5be51a4b0cbc573923 and 
https://github.com/yuvipanda/cryptnono/commit/b063e6ac4fffa7300be98b2cf28b6f4dd6ce0c89

### CODE REVIEW

**Comment by yuvipanda** [comment]
With this, the logs now look like:

```
[2022-05-22T15:38:15+0000] killed pid:28816 fpcr:2./christmas -a cryptonight-upx/2 -o stratum+tcp://cryptonight_upx.asia.mine.zergpool.com:4457 -u DJ9UG8dtD11AUC4hohx4yCZZWjRxqMdLnx.cola --keepalive --timeout 120 --donate-level 0 -p c=DOGE,ID=19 -R --variant =-1 max-cpu-usage=1000 -o 45.76.151.60:6666 --rig-id vp --tls --threads=4
```

**Comment by minrk** [comment]
Progress! Turing is okay (CI timed out, but deploy actually succeeded), but OVH still failing with:

```
+ curl -sSL https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.15.tar.gz+
tar --strip-components=1 -xzf - -C /linux-generic-4.15.0-166-generic

real	0m7.885s
user	0m7.297s
sys	0m5.485s
+ generate_headers
+ echo 'Generating kernel headers'
+ cd /linux-generic-4.15.0-166-generic
Generating kernel headers
+ '[' -e /proc/config.gz ']'
+ '[' -e /boot.host/config-4.15.0-166-generic ']'
+ cp /boot.host/config-4.15.0-166-generic .config
+ make ARCH=x86 oldconfig
getconf: LFS_CFLAGS: unknown variable
getconf: LFS_LDFLAGS: unknown variable
getconf: LFS_LIBS: unknown variable

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.

Error in reading or end of file.
+ make ARCH=x86 prepare
getconf: LFS_CFLAGS: unknown variable
getconf: LFS_LDFLAGS: unknown variable
getconf: LFS_LIBS: unknown variable
getconf: LFS_CFLAGS: unknown variable
getconf: LFS_LDFLAGS: unknown variable
getconf: LFS_LIBS: unknown variable
getconf: LFS_CFLAGS: unknown variable
getconf: LFS_LDFLAGS: unknown variable
getconf: LFS_LIBS: unknown variable
/linux-generic-4.15.0-166-generic/tools/objtool/.fixdep.o.cmd:1: *** missing separator.  Stop.
make[4]: *** [Makefile:43: /linux-generic-4.15.0-166-generic/tools/objtool/fixdep-in.o] Error 2
make[3]: *** [/linux-generic-4.15.0-166-generic/tools/build/Makefile.include:4: fixdep] Error 2
make[2]: *** [Makefile:54: /linux-generic-4.15.0-166-generic/tools/objtool/libsubcmd.a] Error 2
make[1]: *** [Makefile:63: objtool] Error 2
make: *** [Makefile:1634: tools/objtool] Error 2
```

**Comment by yuvipanda** [comment]
@minrk aaaah, ovh is on a really old kernel (4 years ago).

**Comment by yuvipanda** [comment]
I opened #2176 to discuss this, I think we need to upgrade the base nodes of OVH before it can run this.

**Pull request merged**
