### PR TITLE
repo2docker: 25ebca04...91309cab

### PR DESCRIPTION
**Pull request by henchbot**
This is a repo2docker version bump. See the link below for a diff of new changes:

https://github.com/jupyter/repo2docker/compare/25ebca04...91309cab

### CODE REVIEW

**Comment by choldgraf** [comment]
@henchbot were you talking about this PR saying you didn't want it merged yet?

**Comment by henchc** [comment]
@choldgraf yes, if it's not critical, the next commit to repo2docker will allow me to test henchbot updating the PR accordingly, simulating the scenario that nobody got around to merging this for a few days and another commit was pushed. But if you want to merge to test something go for it.

**Comment by choldgraf** [comment]
nah it's fine with me - wanna mark this PR "DNM" at the front of the title or something?

**Comment by henchc** [comment]
Done!

**Comment by betatim** [comment]
A new PR got merged in the repo2docker repo, so if you want to try out henchbot's "update a PR" functionality: go go go :)

**Comment by henchc** [comment]
Looks like this worked and renamed the PR accordingly :)

**Comment by betatim** [comment]
Thanks @henchbot !

**Pull request merged**
