### PR TITLE
preserve host weights when using rendezvous routing

### PR DESCRIPTION
**Pull request by minrk**
rendezvous routing was ignoring our host weights and routing repos uniformly across members.

This algorithm is still routing each repo to one host 100% of the time, so if a repo gets a traffic spike, only one member of the federation will get hit.

### CODE REVIEW

**Comment by consideRatio** [comment]
A function signature is updated to include weights, but how it is called hasn't been updated yet.

https://github.com/jupyterhub/mybinder.org-deploy/blob/c972335b606b0c69b93ac4eb9fe884404f701d04/images/federation-redirect/app.py#L190

To clarify as I was a bit uncertain what "host" referred to, even though I think it refers to for example ovh.mybinder.org or gke.mybinder.org. Is the following a correct summary of the situation?
mybinder.org spreads traffic to various members of the federation, and with rendezvous routing it is now ignoring weights on how to distribute this traffic to the federation members. This PR aims to fix this.

**Comment by minrk** [comment]
@consideRatio good catch, fixed.

**Comment by betatim** [comment]
What problem do we fix by using the weights?

It will change what fraction of repositories are assigned to a cluster. Right now a repository has an equal chance of being assigned to any of the clusters we have available.

In the random assignment case the weights influence the chances of a launch request to be assigned to a particular repo. With rendezvous routing every launch request will be assigned to the same cluster, weights or no weights.

**Comment by minrk** [comment]
Reading about weighted-rendezvous-hashing (WRH), this doesn't actually apply the weights correctly. Need to cast to int and divide by log, etc.

Closing here, and moving to more general discussion in #1066

**Pull request closed without merging**
