### PR TITLE
adding wisdom doc

### PR DESCRIPTION
**Pull request by choldgraf**
A place to put our knowledge / experienced picked up while deploying binder...if anybody can think of other tips I'm happy to put 'em in this PR!

### CODE REVIEW

**Comment by yuvipanda** [comment]
I like it!

**Comment by yuvipanda** [comment]
This should eventually go into the SRE guide @willingc is working on!

**Comment by willingc** [comment]
Cool @choldgraf! Wisdom is a good thing ;-)

Here's the rough SRE guide in a branch on my repo: https://github.com/willingc/mybinder.org-deploy/tree/SRE-guide

[Rendered draft SRE guide](http://test-mybinder-deploy.readthedocs.io/en/sre-guide/)

@choldgraf and @yuvipanda You may find this minimalist guide helpful. I don't want to confuse folks with it in the regular docs, but it's pretty handy for personal use. http://minimalist-jupyterhub.readthedocs.io/en/latest/

**Comment by choldgraf** [comment]
ah I really like that SRE guide...apologies if this has already been figured out (I'm just getting back from way too much conferencing) but are there plans to merge that into `mybinder.org`? I think it's a good idea!

**Comment by willingc** [comment]
Yep @choldgraf, that's the plan. I just haven't gotten a chance yet to loop back to it.

**Pull request merged**
