### PR TITLE
Add more deployment docs + cleanup

### PR DESCRIPTION
**Pull request by yuvipanda**
- Add a doc on what happens during a deployment, with list
  of common things that go wrong
- Cleanup existing deployment documentation and consolidate it
  under a deployment directory

### CODE REVIEW

**Comment by yuvipanda** [comment]
i'm going to spend rest of my day re-organizing and completing the other deployment related documentation here.

**Comment by choldgraf** [comment]
🥇 

I'm +1 but will wait for @willingc to give her thoughts since she took a look as well!

**Comment by yuvipanda** [comment]
@choldgraf I actually ended up using this PR to do a *lot* more cleanup around deployment docs. Do take a look! :)

I still need to actually flesh out the deployment policy doc, and add a deployment philosophy doc.

**Comment by choldgraf** [comment]
are you planning to add more to _this_ PR? AKA should I wait until more stuff is added?

**Comment by yuvipanda** [comment]
@choldgraf ah, no I think this one is good to go, mostly because I've to leave now! :D will add new docs to a hackmd first, and go through this process.

I wish GitHub had 'dependent PRs' :(

**Comment by yuvipanda** [comment]
Thanks, @choldgraf!

**Pull request merged**
