### PR TITLE
Revert docker hub registry URL changes for Turing, it's fixed in upstream Binderhub

### PR DESCRIPTION
**Pull request by MridulS**
This PR reverts https://github.com/jupyterhub/mybinder.org-deploy/pull/1937

The following config is **removed** from Turing cluster:
```
config:
  DockerRegistry:
    url: "https://registry-1.docker.io"
    auth_config_url: "https://index.docker.io/v1"
    token_url: "https://auth.docker.io/token?service=registry.docker.io"
```

Binderhub has the updated registry URL https://github.com/jupyterhub/binderhub/pull/1334

### CODE REVIEW

**Comment by yuvipanda** [comment]
@MridulS do you know how we can test this? I'm a bit out of the loop

**Comment by MridulS** [comment]
I'm not sure if there is a best way to test this before deploy but depending on how YOLO you are feeling, feel free to go ahead and merge this in and I can keep an eye out on the Turing cluster. To check if everything is okay, something like https://turing.mybinder.org/v2/gh/binder-examples/requirements/HEAD should open up directly by using the built image and not to try build it again.

I just reverted the changes at GESIS and everything looks okay here (we use docker hub too).

**Comment by yuvipanda** [comment]
Hmm, so https://github.com/jupyterhub/mybinder.org-deploy/pull/1984 was the last binderhub bump - and I don't think it includes your changes. So maybe henchbot didn't pick up that merge?

**Comment by MridulS** [comment]
ahh yes, it hasn't yet.

The change would still work because Docker folks anyway brought up the old registry URL too, but they did mention that `https://registry-1.docker.io` is the recommended one.

**Comment by consideRatio** [comment]
BinderHub is patched in https://github.com/jupyterhub/mybinder.org-deploy/pull/1991, I'll go for a merge here.

**Pull request merged**
