### PR TITLE
Create GitLab actions to trigger update in GESIS

### PR DESCRIPTION
**Pull request by rgaiacs**
This pull request creates a GitHub action that will make a HTTP request to GESIS and trigger the update of GESIS Kubernetes cluster.

I prefer to have this as a GitHub action instead of [GitHub native webhook](https://docs.github.com/en/webhooks-and-events/webhooks/about-webhooks) for transparency.

This pull request requires a secret (`GESIS_TOKEN`) to be added to this repository. Can I be contacted in private to share the secret?

### CODE REVIEW

**Comment by manics** [comment]
Other than the pre-commit/formatting error this seems fine to me.

**Comment by minrk** [comment]
I have added the GESIS_TOKEN secret from @rgaiacs

**Comment by rgaiacs** [comment]
I think it is ready to merge.

**Comment by rgaiacs** [comment]
Thanks @manics. Things looks good on GESIS side.

**Pull request merged**
