### PR TITLE
[MRG] deploy both production clusters then test both

### PR DESCRIPTION
**Pull request by henchc**
Thought I would take the opportunity for what seemed to me like a good entry-PR on the build process here addressing issue #1023

### CODE REVIEW

**Comment by betatim** [comment]
Looks good to me. Time to merge or do you want to keep working on it ([WIP] in the title)?

**Comment by henchc** [comment]
Great! Just wanted to make sure I didn't miss something :) .

**Comment by choldgraf** [comment]
The change looks good to me! Could you quickly summarize the main benefit of this? Is the goal to minimize the time over out-of-sync-ness between the clusters?

**Comment by betatim** [comment]
Sometimes the test of GKE fails (for no good reason) and we end up not deploying to OVH.

I think it would be good to first do the two deploys and then test both of them. This way we keep the two clusters more consistent. If there is something actually wrong with the setup we will still get a failure that we have to deal with.

Just feels like we get flakey tests that lead to a difference in deployed versions/config more often than an actual test failure on GKE that saves us from also breaking OVH.

And unless we make a catastrophic configuration error things would work well enough for the federation proxy to keep sending traffic to the broken GKE cluster. So we don't get the benefit of "well, let's stop deploying before we hose everything". We should revisit this deploy-deploy-test-test choice when we make the federation redirector smarter.

**Comment by henchc** [comment]
I would +1 this, I've gotten odd timeout failures that may not be the upgrades fault in the first place, and now with the other hub it would deploy one and not the other. I don't think this is a major change for that, but at least you would fully upgrade/revert both together. But I would defer to @betatim given his experience here.

**Comment by betatim** [comment]
Merged. If it starts being annoying or doing the wrong thing we can easily switch back to the old behaviour.

**Pull request merged**
