### PR TITLE
repo2docker: 0.10.0-112.g242107b...0.10.0-80.g2ee3230

### PR DESCRIPTION
**Pull request by henchbot**
This is a repo2docker version bump. See the link below for a diff of new changes:

https://github.com/jupyter/repo2docker/compare/242107b...2ee3230 

Associated PRs:

### CODE REVIEW

**Comment by betatim** [comment]
Not sure what henchbot was thinking so I closed this.

**Comment by betatim** [comment]
I think it should have changed the image tag to 0.10.0-117.g3337eaa

**Comment by bitnik** [comment]
But compare link is still wrong

**Comment by betatim** [comment]
Nods, I think henchbot is totally confused :(

**Pull request closed without merging**
