### PR TITLE
repo2docker: 0.11.0-5.g8d490cf...0.10.0-144.geb0ea0a

### PR DESCRIPTION
**Pull request by henchbot**
This is a repo2docker version bump. See the link below for a diff of new changes:

https://github.com/jupyter/repo2docker/compare/8d490cf...eb0ea0a 

Associated PRs:

### CODE REVIEW

**Comment by betatim** [comment]
Let's not merge this until we understand why it takes us back to an old tag

**Comment by henchc** [comment]
This has been happening for a while, I'm not sure why but for a span of ca. 30 minutes it will have the wrong hash, then it corrects itself, I can look closer this weekend but is it possible a temporary commit is published immediately which is updated later?

**Comment by henchc** [comment]
Also, this only happens for repo2docker, not binderhub

**Comment by betatim** [comment]
Weird. I have no good idea what could be happening to trigger this.

**Comment by bitnik** [comment]
I have guess: docker hub API

Sometimes when I checks tags of a repo manually, I see that latest tag is not the first one in the list. And henchbot gets list the list of tags from https://hub.docker.com/v2/repositories/jupyter/repo2docker/tags/ and then selects the first one as latest tag of repo2docker. Maybe API also returns an unordered list for a while.

**Comment by betatim** [comment]
That is true, I also have to click reload on the list of tags "every time" I visit a repo on docker hub. Good idea!

**Comment by henchc** [comment]
Thanks @bitnik ! I'll see if I can fix this.

**Pull request closed without merging**
