### PR TITLE
grafana: install histogram panel

### PR DESCRIPTION
**Pull request by minrk**
could help in visualizing histogram data

which we are using for timing build/launch/etc.

### CODE REVIEW

**Comment by betatim** [comment]
Merge?

**Comment by minrk** [comment]
I would like that, yes :)

**Comment by choldgraf** [comment]
@minrk what's a pattern we can use with this to test it out on https://grafana.staging.mybinder.org/?orgId=1 before merging into prod?

**Comment by betatim** [comment]
https://grafana.mybinder.org/render/dashboard-solo/db/main-dashboard?refresh=1m&orgId=1&from=1516870983117&to=1516914183117&panelId=4&width=1000&height=500&tz=UTC%2B01%3A00

Any idea what happened there? This is from grafana.mybinder.org so really shouldn't be connected to this PR, but this was the only PR merged this afternoon?

**Pull request merged**
