### PR TITLE
Pin Sphinx to <3

### PR DESCRIPTION
**Pull request by manics**
The docs build failed in https://github.com/jupyterhub/mybinder.org-deploy/pull/1410
```
#!/bin/bash -eo pipefail
cd docs
make html

Running Sphinx v3.0.1
making output directory... done

Theme error:
no theme named 'pandas_sphinx_theme' found (missing theme.conf?)
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2

Exited with code exit status 2
```
https://circleci.com/gh/jupyterhub/mybinder.org-deploy/433

This is to see whether it's due to the new release of Sphinx.

### CODE REVIEW

**Comment by choldgraf** [comment]
This one also needs to change the theme to `pydata_sphinx_theme` throughout the installs / extension load as well

**Comment by betatim** [comment]
So the problem is the wrongly named theme not the sphinx version?

**Comment by choldgraf** [comment]
well they might both be problems - Sphinx 3 (or, as this PR makes me think, Sphinx ❤️) was just released and does have a few bugs that have come with it (e.g., https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1628). I think to be safe, we might as well wait for 3.1 to let some of the bugs be worked out, or to wait for documentation to surface showing how to get around any errors and API changes

**Comment by manics** [comment]
I've changed the theme to `pydata_sphinx_theme`.

I've also opened an alternative PR that may fix the Sphinx 3 errors: https://github.com/jupyterhub/mybinder.org-deploy/pull/1414. Take your pick 🙂

**Comment by betatim** [comment]
Closing because i merged #1414. Forwards to the brave new future :)

**Pull request closed without merging**
