### PR TITLE
Add pod health check notebook

### PR DESCRIPTION
**Pull request by minrk**
Notebook that inspects the state of jupyterhub and running pods and creates a simple report, including identification of probable orphaned pods (i.e. user pods with no corresponding user registered with JupyterHub).

Example report from running earlier today:

screen shot 2017-11-29 at 14 59 24

Includes functions for deleting the orphaned pods if so desired.

### CODE REVIEW

**Comment by choldgraf** [comment]
this is so cool! could we include a `binder/` folder w/ requirements needed
to run the notebook? That way we could run this from binder!

Also, I had put together a binder-stats repo to do analytics on binder.
Perhaps I should get rid of that and put it here? Or we should put this
notebook into `binder-stats` and make it part of the JupyterHub org?

https://github.com/choldgraf/binder-stats

**Comment by yuvipanda** [comment]
This is awesome!

I don't believe you can run this from inside binder though, since it needs authentication to both kubernetes API

**Comment by minrk** [comment]
I'm fine either way, I don't think I have a strong preference for whether it goes here or a dedicated repo, but as @yuvipanda pointed out, this must be run in a context with access to the deployment (i.e. on your own machine).

**Comment by choldgraf** [comment]
ya I agree it'd be better in this repo too, didn't think about the credentials thing. Thanks @minrk !

**Pull request merged**
