### PR TITLE
Bumping bluesky/tutorials to 300 quota

### LINKED ISSUE #1430: Increase limit to 200 for NEUBIAS course
Hi,

I'm Guillaume Witz from Bern University. I'm a bioimage analyst for the Microscopy Imaging Center, and I have been asked by the Network of European BioImage Analyst (NEUBIAS, a European COST action http://eubias.org/NEUBIAS/) to give a course on Image processing with Python and Jupyter (http://eubias.org/NEUBIAS/training-schools/neubias-academy-home/) in the frame of their special webinar series organised for scientist who have to work from home.

All the courses of this series are free to attend. People can register for live sessions on Zoom, and the recording of the course is then also published on Youtube. The speakers provide this training without compensation, in the frame of their jobs as bioimage analysts or researchers at various Universities.

The course on Python and Jupyter is available in interactive form thanks to the mybinder.org service and can be found here: https://github.com/guiwitz/neubias_academy_biapy. The course has the following structure: on 7th of May 15.30-17.00 (Brussels time), participants are introduced to the material (including mybinder.org) service during webinar. Students can then explore the material for a week on their own using the interactive binder session. A second webinar takes place on 13th of May 15.30-17.00 (Brussels time) where the material is further explained. At the time of writing, 500 participants registered.

We do not expect 500 participants to work at the exact same time, and it will be made clear that not all participants should connect simultaneously during the webinar. Still this repository might generate a lot of traffic. This GitHub issue serves therefore as a warning for the maintainers of this service.

Thanks for this great service that you provide!

Guillaume

### PR DESCRIPTION
**Pull request by choldgraf**
closes #1430 since that course is now done, and adds @tacaswell's course that he just requested in #1438 

I'm gonna merge this in on short notice, but in the future @tacaswell please give us a bit more heads up than 15 minutes :-)

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you so much :tada:  !  We will definitely do a better job planning a head next time.

**Comment by mrakitin** [comment]
Thanks @choldgraf!

**Comment by choldgraf** [comment]
let us know if the quota works, BTW

**Comment by mrakitin** [comment]
Now I can start the session! How do we track how many people are connected? @tacaswell announced the new temp limit to the audience.

**Comment by tacaswell** [comment]
https://grafana.mybinder.org/d/fZWsQmnmz/pod-activity?orgId=1&refresh=1m&from=now-12h&to=now&var-cluster=default is what I am watching.

**Comment by mrakitin** [comment]
Neat :)

**Comment by tacaswell** [comment]
We got no more complaints, but we also had some people who gave up trying to follow along.

We have more or less wrapped up.  I would be happy to have the quota reverted.

**Pull request merged**
