### PR TITLE
analytics-publisher: fix for breaking binderhub change, refreeze dependencies, modernize Dockerfile

### LINKED ISSUE #2392: analytics-publisher is crashing due to a breaking change in binderhub
@yuvipanda wrote:

> https://archive.analytics.mybinder.org/ looks like it stopped last week

Inspection gave me that the pod was unhealthy and failing to start.

```
analytics-publisher                 0/1     1            0           2y2d
```

```
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Normal   Pulled   32m (x2756 over 24d)    kubelet  Container image "jupyterhub/mybinder.org-analytics-publisher:2020.12.4-0.dev.git.4529.h99dd8b0" already present on machine
  Warning  BackOff  2m51s (x64858 over 9d)  kubelet  Back-off restarting failed container
```

The following logs were seen

```
Archiving today's events 2022-10-30
Finding blobs with prefix binderhub-events-text/2022/10/30
Traceback (most recent call last):
  File "/srv/run.py", line 34, in <module>
    archive_events(
  File "/srv/archiver.py", line 54, in archive_events
    event = json.loads(json.loads(line)["jsonPayload"]["message"])
KeyError: 'message'
```

## Understanding what caused this

The line of code that fails

https://github.com/jupyterhub/mybinder.org-deploy/blob/9ef1ae26eee45e4dbabacbc595f765a486ae3f4f/images/analytics-publisher/archiver.py#L38-L54

The configuration of source bucket for prod

https://github.com/jupyterhub/mybinder.org-deploy/blob/9ef1ae26eee45e4dbabacbc595f765a486ae3f4f/config/prod.yaml#L201-L206

The [GCP bucket](https://console.cloud.google.com/storage/browser/binder-events-raw-export;tab=objects?forceOnBucketsSortingFiltering=false&authuser=2&project=binderhub-288415&prefix=&forceOnObjectsSortingFiltering=false)

The uploaded data are lines of JSON objects, where how each object looks has changed.

### Before

```json
{
    "insertId": "d1iovxfoalkix",
    "jsonPayload": {
        "message": "{\"timestamp\": \"2022-10-16T00:10:39.415163Z\", \"schema\": \"binderhub.jupyter.org/launch\", \"version\": 5, \"provider\": \"GitHub\", \"spec\": \"spyder-ide/spyder/5.x\", \"ref\": \"a76b6f09d692ebf09049fb83d26c1e7e669fbaa6\", \"status\": \"success\", \"build_token\": true, \"origin\": \"ovh.mybinder.org\"}",
        "python_logger": null
    },
    "logName": "projects/binderhub-288415/logs/binderhub-events-text",
    "receiveTimestamp": "2022-10-16T00:10:39.482690331Z",
    "resource": {
        "labels": {
            "project_id": "binderhub-288415"
        },
        "type": "global"
    },
    "severity": "INFO",
    "timestamp": "2022-10-16T00:10:39.415195Z"
}
```

where the "jsonPayload.message" field is a string of JSON that would parse like this:

```
{
    "timestamp": "2022-10-16T00:10:39.415163Z",
    "schema": "binderhub.jupyter.org/launch",
    "version": 5,
    "provider": "GitHub",
    "spec": "spyder-ide/spyder/5.x",
    "ref": "a76b6f09d692ebf09049fb83d26c1e7e669fbaa6",
    "status": "success",
    "build_token": true,
    "origin": "ovh.mybinder.org"
}
```

### After

With 2022-10-20 - 11:00 and onwards, a new format started showing that didn't include `jsonPayload.message`.

```json
{
    "insertId": "1de0btlfd1znx0",
    "jsonPayload": {
        "build_token": true,
        "origin": "gesis.mybinder.org",
        "provider": "GitLab",
        "ref": "18b0c773b170ce45b23547f135e783174e81c18f",
        "schema": "binderhub.jupyter.org/launch",
        "spec": "comp2421-numerical-computation%2Fbook/master",
        "status": "success",
        "timestamp": "2022-10-30T00:00:37.591502Z",
        "version": 5
    },
    "labels": {
        "python_logger": "binderhub.events"
    },
    "logName": "projects/binderhub-288415/logs/binderhub-events-text",
    "receiveTimestamp": "2022-10-30T00:00:37.641295756Z",
    "resource": {
        "labels": {
            "project_id": "binderhub-288415"
        },
        "type": "global"
    },
    "severity": "INFO",
    "sourceLocation": {
        "file": "<string>",
        "function": "emit",
        "line": "25"
    },
    "timestamp": "2022-10-30T00:00:37.591546Z"
}
```

### Hypothesis concluded

After 2022-10-20 (about 11:00), the `jsonPayload` changed its structure, where `jsonPayload.message` is unpacked directly in `jsonPayload` it seems.

This coincides with https://github.com/jupyterhub/mybinder.org-deploy/pull/2369, which in turn includes this changes

image

That in turn comes from https://github.com/jupyterhub/binderhub/pull/1536

## Action points

- [x] Open an issue about catching this failure on deployment to staging
  https://github.com/jupyterhub/mybinder.org-deploy/issues/2391
- [x] Resolve failure using one option below
  1. To adjust analytics-publisher parsing uploaded data
     We could make analytics-publisher script adjust to the new format, or if needed, attempt to parse either.
     #2393 
  2. To adjust binderhub uploads data
     We could make binderhub, using google's logger library, manage to retain the format we used previously somehow.
  3. Downgrading software in binderhubs image
     Using v1 [caused a problem](https://github.com/jupyterhub/binderhub/pull/1536) bound to happen sooner or later, so working around it would just give us some time at best - and be an effort to do by itself.
     
I suggest resolving it with adjusting analytics-publisher's parsing of uploaded data in this location

https://github.com/jupyterhub/mybinder.org-deploy/blob/9ef1ae26eee45e4dbabacbc595f765a486ae3f4f/images/analytics-publisher/archiver.py#L38-L54

### PR DESCRIPTION
**Pull request by consideRatio**
- Closes #2392

Also adops a pattern reducing final build size and improves build speed, as invented by @minrk in a z2jh PR a while back.

### CODE REVIEW

**Comment by manics** [comment]
The fix for r.org-deploy/issues/2392 LGTM

/test-this-pr

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2393).

**Comment by consideRatio** [comment]
Thanks @manics for reviewing! I did a force push adjusting the last commit regarding a detail change to coalesce on /tmp/wheels as a location both in the build-stage and final stage on where things are stored.

/test-this-pr

**Comment by sgibson91** [comment]
This Pull Request is now being tested :tada: See the test progress in [GitHub Actions](https://github.com/jupyterhub/mybinder.org-deploy/actions?query=branch%3Atest-this-pr%2F2393).

**Comment by consideRatio** [comment]
Seems to work on staging, but can't say for sure unless events are actually uploaded.

```
$ kubectl logs analytics-publisher-6dbfc66585-ngb5f

Archiving today's events 2022-10-30
Finding blobs with prefix binderhub-staging-events-text/2022/10/30
Uploaded binder-staging-events-archive/events-2022-10-30.jsonl with 0 events
```

**Pull request merged**
